const en = {
  appName: "Travel Explorer",
  splashTagline: "Explore more. Worry less.",
  skip: "Skip",
  next: "Next",
  getStarted: "Get Started",
  onboarding1Title: "Life is brief, but the world is vast.",
  onboarding1Description:
    "Curated journeys, inspiring places, and travel plans that make every trip feel effortless.",
  onboarding2Title: "The world is waiting for you.",
  onboarding2Description:
    "Discover beaches, cities, islands, deserts, and hidden gems beyond your comfort zone.",
  onboarding3Title: "Trips become stories worth keeping.",
  onboarding3Description:
    "Save favorite places, plan your schedule, and travel with confidence from day one.",
  signInNow: "Sign in now",
  signUpNow: "Sign up now",
  pleaseSignIn: "Please sign in to continue our app",
  pleaseSignUp: "Please fill the details and create account",
  fullName: "Full name",
  email: "Email",
  password: "Password",
  passwordHint: "Password must be at least 8 characters",
  forgotPassword: "Forgot password?",
  forgotPasswordTitle: "Forgot password",
  forgotPasswordSubtitle: "Enter your email account to reset your password",
  resetPassword: "Reset Password",
  checkEmail: "Check your email",
  checkEmailMessage: "We have sent password recovery instructions to your email.",
  signIn: "Sign In",
  signUp: "Sign Up",
  noAccount: "Don't have an account?",
  haveAccount: "Already have an account?",
  discoverTitle: "Discover the wonders of the world!",
  bestDestination: "Best Destination",
  popularPlaces: "Popular Places",
  allPopularPlaces: "All Popular Places",
  popularPackages: "Popular Package",
  allPopularTripPackage: "All Popular Trip Package",
  favoritePlaces: "Favorite Places",
  noFavorites: "No favorite places",
  noFavoritesMessage: "Tap the heart on any place to keep it here.",
  schedule: "Schedule",
  mySchedule: "My Schedule",
  search: "Search",
  searchPlaces: "Search Places",
  notification: "Notification",
  clearAll: "Clear all",
  recent: "Recent",
  earlier: "Earlier",
  archived: "Archived",
  aiChat: "AI Chat",
  aiTravelAssistant: "Travel AI Assistant",
  aiChatSubtitle: "Ask for itineraries, budgets, packing tips, and destination ideas.",
  askAiPlaceholder: "Ask your travel AI...",
  aiQuickBeach: "Plan a beach weekend",
  aiQuickBudget: "Suggest a budget trip",
  aiQuickPacking: "Packing checklist",
  aiQuickVietnam: "Vietnam itinerary",
  aiThinking: "Thinking",
  cancel: "Cancel",
  viewAll: "View all",
  bookNow: "Book Now",
  aboutDestination: "About Destination",
  person: "Person",
  joined: "joined",
  perPerson: "Person",
  reviews: "reviews",
  home: "Home",
  calendar: "Calendar",
  profile: "Profile",
  editProfile: "Edit Profile",
  changeProfilePicture: "Change Profile Picture",
  rewardPoints: "Reward Points",
  travelTrips: "Travel Trips",
  bucketList: "Bucket List",
  bookmarked: "Bookmarked",
  previousTrips: "Previous Trips",
  settings: "Settings",
  verification: "Verification",
  version: "Version",
  done: "Done",
  firstName: "First Name",
  lastName: "Last Name",
  location: "Location",
  mobileNumber: "Mobile Number",
  otpVerification: "OTP Verification",
  otpDescription: "Please check your email imanefh28@gmail.com to see the verification code",
  otpCode: "OTP Code",
  verify: "Verify",
  resendCodeTo: "Resend code to",
  theme: "Theme",
  lightMode: "Light",
  darkMode: "Dark",
  language: "Language",
  english: "EN",
  vietnamese: "VI",
  noResults: "No results found",
  noResultsMessage: "Try another keyword or explore popular places.",
  loading: "Loading",
};

export default en;
