const en = {
  appName: "Travel Explorer",
  splashTagline: "Explore more. Worry less.",
  skip: "Skip",
  next: "Next",
  getStarted: "Get Started",
  onboarding1Title: "Life is brief, but the world is vast.",
  onboarding1Description:
    "Curated journeys, inspiring places, and travel plans that make every trip feel effortless.",
  onboarding2Title: "The world is waiting for you.",
  onboarding2Description:
    "Discover beaches, cities, islands, deserts, and hidden gems beyond your comfort zone.",
  onboarding3Title: "Trips become stories worth keeping.",
  onboarding3Description:
    "Save favorite places, book destinations, and travel with confidence from day one.",
  signInNow: "Sign in now",
  signUpNow: "Sign up now",
  pleaseSignIn: "Please sign in to continue our app",
  pleaseSignUp: "Please fill the details and create account",
  fullName: "Full name",
  flexible: "Flexible",
  email: "Email",
  password: "Password",
  passwordHint: "Password must be at least 8 characters",
  fullNameRequired: "Please enter your full name.",
  emailRequired: "Please enter your email.",
  invalidEmail: "Please enter a valid email address.",
  passwordRequired: "Please enter your password.",
  passwordTooShort: "Password must be at least 8 characters.",
  forgotPassword: "Forgot password?",
  forgotPasswordTitle: "Forgot password",
  forgotPasswordSubtitle: "Enter your email account to reset your password",
  resetPassword: "Reset Password",
  checkEmail: "Check your email",
  checkEmailMessage: "We have sent password recovery instructions to your email.",
  signIn: "Sign In",
  signUp: "Sign Up",
  sendingOtp: "Sending OTP...",
  noAccount: "Don't have an account?",
  haveAccount: "Already have an account?",
  discoverTitle: "Discover the wonders of the world!",
  bestDestination: "Best Destination",
  popularPlaces: "Popular Places",
  allPopularPlaces: "All Popular Places",
  popularPackages: "Popular Package",
  allPopularTripPackage: "All Popular Trip Package",
  about: "About",
  aboutAppTitle: "About the App",
  aboutAppDescription:
    "Travel Explorer helps travelers discover destinations, save favorite places, book trips, and get practical AI travel suggestions in one mobile experience.",
  aboutTeamTitle: "About the Team",
  aboutTeamDescription:
    "We are a small product team focused on making travel planning clearer, faster, and more enjoyable through thoughtful design and useful technology.",
  aboutValueAi: "AI tips",
  aboutValueExplore: "Explore",
  aboutValueSave: "Save places",
  favoritePlaces: "Favorite Places",
  noFavorites: "No favorite places",
  noFavoritesMessage: "Tap the heart on any place to keep it here.",
  search: "Search",
  searchPlaces: "Search Places",
  notification: "Notification",
  clearAll: "Clear all",
  recent: "Recent",
  readMore: "Read More",
  earlier: "Earlier",
  archived: "Archived",
  aiChat: "AI Chat",
  aiTravelAssistant: "Travel AI Assistant",
  aiChatSubtitle: "Ask for itineraries, budgets, packing tips, and destination ideas.",
  askAiPlaceholder: "Ask your travel AI...",
  aiQuickBeach: "Plan a beach weekend",
  aiQuickBudget: "Suggest a budget trip",
  aiQuickPacking: "Packing checklist",
  aiQuickVietnam: "Vietnam itinerary",
  aiThinking: "Thinking",
  cancel: "Cancel",
  viewAll: "View all",
  bookNow: "Book Now",
  bookingConfirmed: "Booking confirmed",
  bookingDetails: "Booking Details",
  bookingFailed: "Unable to book this trip",
  bookings: "Bookings",
  aboutDestination: "About Destination",
  guests: "Guests",
  myBookings: "My Bookings",
  noBookings: "No bookings yet",
  noBookingsMessage: "Book a destination and your confirmed trips will appear here.",
  person: "Person",
  joined: "joined",
  perPerson: "Person",
  reviews: "reviews",
  home: "Home",
  profile: "Profile",
  editProfile: "Edit Profile",
  changeProfilePicture: "Change Profile Picture",
  imageTooLarge: "Please choose a smaller image.",
  imageUrl: "Image URL",
  imageUrlRequired: "Please paste an image URL.",
  invalidImageUrl: "Please paste a valid image URL.",
  pasteImageUrl: "Paste image URL",
  photoPermissionDenied: "Photo library permission is required.",
  profilePhoto: "Profile Photo",
  removePhoto: "Remove Photo",
  uploadPhoto: "Upload Photo",
  useImageUrl: "Use Image URL",
  rewardPoints: "Reward Points",
  travelTrips: "Travel Trips",
  bucketList: "Bucket List",
  bookmarked: "Bookmarked",
  previousTrips: "Previous Trips",
  contactAndPolicy: "Contact & Policy",
  contactInfo: "Contact Information",
  logout: "Logout",
  privacyPolicy: "Privacy Policy",
  privacyPolicyText:
    "We only collect information needed to provide account, booking, favorite place, and travel assistant features. Your contact information is used for authentication, support, and trip updates.",
  socialNetworks: "Social Networks",
  termsOfUse: "Terms of Use",
  termsOfUseText:
    "By using Travel Explorer, you agree to provide accurate booking information, respect service rules, and use AI suggestions as travel guidance rather than final legal or safety advice.",
  verification: "Verification",
  version: "Version",
  done: "Done",
  firstName: "First Name",
  lastName: "Last Name",
  location: "Location",
  mobileNumber: "Mobile Number",
  otpVerification: "OTP Verification",
  otpDescription: "Please check your email to see the verification code",
  otpCode: "OTP Code",
  verify: "Verify",
  signInToBook: "Please sign in to book this destination.",
  status: "Status",
  total: "Total",
  travelDate: "Travel Date",
  resendCodeTo: "Resend code to",
  theme: "Theme",
  lightMode: "Light",
  darkMode: "Dark",
  language: "Language",
  english: "EN",
  vietnamese: "VI",
  noResults: "No results found",
  noResultsMessage: "Try another keyword or explore popular places.",
  loading: "Loading",
  loadDataError: "Unable to load app data",
  retry: "Try Again",
};

export default en;
