import en from "./en";

const vi: typeof en = {
  appName: "Travel Explorer",
  splashTagline: "Đi nhiều hơn. Lo ít hơn.",
  skip: "Bỏ qua",
  next: "Tiếp tục",
  getStarted: "Bắt đầu",
  onboarding1Title: "Đời ngắn, nhưng thế giới thì rộng lớn.",
  onboarding1Description:
    "Những hành trình được tuyển chọn, điểm đến truyền cảm hứng và kế hoạch du lịch thật nhẹ nhàng.",
  onboarding2Title: "Thế giới đang chờ bạn khám phá.",
  onboarding2Description:
    "Tìm bãi biển, thành phố, đảo, sa mạc và những viên ngọc ẩn bên ngoài vùng quen thuộc.",
  onboarding3Title: "Mỗi chuyến đi là một câu chuyện đáng giữ.",
  onboarding3Description:
    "Lưu địa điểm yêu thích, lên lịch trình và bắt đầu hành trình với sự tự tin.",
  signInNow: "Đăng nhập ngay",
  signUpNow: "Tạo tài khoản",
  pleaseSignIn: "Vui lòng đăng nhập để tiếp tục",
  pleaseSignUp: "Điền thông tin để tạo tài khoản",
  fullName: "Họ và tên",
  email: "Email",
  password: "Mật khẩu",
  passwordHint: "Mật khẩu cần ít nhất 8 ký tự",
  forgotPassword: "Quên mật khẩu?",
  forgotPasswordTitle: "Quên mật khẩu",
  forgotPasswordSubtitle: "Nhập email để đặt lại mật khẩu",
  resetPassword: "Đặt lại mật khẩu",
  checkEmail: "Kiểm tra email",
  checkEmailMessage: "Chúng tôi đã gửi hướng dẫn khôi phục mật khẩu tới email của bạn.",
  signIn: "Đăng nhập",
  signUp: "Đăng ký",
  noAccount: "Chưa có tài khoản?",
  haveAccount: "Đã có tài khoản?",
  discoverTitle: "Khám phá những kỳ quan của thế giới!",
  bestDestination: "Điểm đến nổi bật",
  popularPlaces: "Địa điểm phổ biến",
  allPopularPlaces: "Tất cả địa điểm phổ biến",
  popularPackages: "Gói du lịch nổi bật",
  allPopularTripPackage: "Tất cả gói du lịch",
  favoritePlaces: "Địa điểm yêu thích",
  noFavorites: "Chưa có địa điểm yêu thích",
  noFavoritesMessage: "Chạm biểu tượng trái tim ở địa điểm bất kỳ để lưu tại đây.",
  schedule: "Lịch trình",
  mySchedule: "Lịch của tôi",
  search: "Tìm kiếm",
  searchPlaces: "Tìm địa điểm",
  notification: "Thông báo",
  clearAll: "Xóa tất cả",
  recent: "Gần đây",
  earlier: "Trước đó",
  archived: "Đã lưu trữ",
  aiChat: "AI Chat",
  aiTravelAssistant: "Trợ lý du lịch AI",
  aiChatSubtitle: "Hỏi lịch trình, ngân sách, hành lý và ý tưởng điểm đến.",
  askAiPlaceholder: "Hỏi AI du lịch...",
  aiQuickBeach: "Lên lịch cuối tuần biển",
  aiQuickBudget: "Gợi ý chuyến tiết kiệm",
  aiQuickPacking: "Checklist hành lý",
  aiQuickVietnam: "Lịch trình Việt Nam",
  aiThinking: "Đang nghĩ",
  cancel: "Hủy",
  viewAll: "Xem tất cả",
  bookNow: "Đặt ngay",
  aboutDestination: "Về điểm đến",
  person: "Người",
  joined: "đã tham gia",
  perPerson: "Người",
  reviews: "đánh giá",
  home: "Trang chủ",
  calendar: "Lịch",
  profile: "Hồ sơ",
  editProfile: "Sửa hồ sơ",
  changeProfilePicture: "Đổi ảnh đại diện",
  rewardPoints: "Điểm thưởng",
  travelTrips: "Chuyến đi",
  bucketList: "Bucket List",
  bookmarked: "Đã lưu",
  previousTrips: "Chuyến đi trước",
  settings: "Cài đặt",
  verification: "Xác thực",
  version: "Phiên bản",
  done: "Xong",
  firstName: "Tên",
  lastName: "Họ",
  location: "Vị trí",
  mobileNumber: "Số điện thoại",
  otpVerification: "Xác thực OTP",
  otpDescription: "Vui lòng kiểm tra email imanefh28@gmail.com để xem mã xác thực",
  otpCode: "Mã OTP",
  verify: "Xác thực",
  resendCodeTo: "Gửi lại mã đến",
  theme: "Giao diện",
  lightMode: "Sáng",
  darkMode: "Tối",
  language: "Ngôn ngữ",
  english: "EN",
  vietnamese: "VI",
  noResults: "Không tìm thấy kết quả",
  noResultsMessage: "Thử từ khóa khác hoặc khám phá các địa điểm phổ biến.",
  loading: "Đang tải",
};

export default vi;
