import en from "./en";

const vi: typeof en = {
  appName: "Travel Explorer",
  splashTagline: "Đi nhiều hơn. Lo ít hơn.",
  skip: "Bỏ qua",
  next: "Tiếp tục",
  getStarted: "Bắt đầu",
  onboarding1Title: "Đời ngắn, nhưng thế giới thì rộng lớn.",
  onboarding1Description:
    "Những hành trình được tuyển chọn, điểm đến truyền cảm hứng và kế hoạch du lịch thật nhẹ nhàng.",
  onboarding2Title: "Thế giới đang chờ bạn khám phá.",
  onboarding2Description:
    "Tìm bãi biển, thành phố, đảo, sa mạc và những viên ngọc ẩn bên ngoài vùng quen thuộc.",
  onboarding3Title: "Mỗi chuyến đi là một câu chuyện đáng giữ.",
  onboarding3Description:
    "Lưu địa điểm yêu thích, đặt điểm đến và bắt đầu hành trình với sự tự tin.",
  signInNow: "Đăng nhập ngay",
  signUpNow: "Tạo tài khoản",
  pleaseSignIn: "Vui lòng đăng nhập để tiếp tục",
  pleaseSignUp: "Điền thông tin để tạo tài khoản",
  fullName: "Họ và tên",
  flexible: "Linh hoạt",
  email: "Email",
  password: "Mật khẩu",
  passwordHint: "Mật khẩu cần ít nhất 8 ký tự",
  fullNameRequired: "Vui lòng nhập họ và tên.",
  emailRequired: "Vui lòng nhập email.",
  invalidEmail: "Vui lòng nhập email hợp lệ.",
  passwordRequired: "Vui lòng nhập mật khẩu.",
  passwordTooShort: "Mật khẩu cần ít nhất 8 ký tự.",
  forgotPassword: "Quên mật khẩu?",
  forgotPasswordTitle: "Quên mật khẩu",
  forgotPasswordSubtitle: "Nhập email để đặt lại mật khẩu",
  resetPassword: "Đặt lại mật khẩu",
  checkEmail: "Kiểm tra email",
  checkEmailMessage: "Chúng tôi đã gửi hướng dẫn khôi phục mật khẩu tới email của bạn.",
  signIn: "Đăng nhập",
  signUp: "Đăng ký",
  sendingOtp: "Đang gửi OTP...",
  noAccount: "Chưa có tài khoản?",
  haveAccount: "Đã có tài khoản?",
  discoverTitle: "Khám phá những kỳ quan của thế giới!",
  bestDestination: "Điểm đến nổi bật",
  popularPlaces: "Địa điểm phổ biến",
  allPopularPlaces: "Tất cả địa điểm phổ biến",
  popularPackages: "Gói du lịch nổi bật",
  allPopularTripPackage: "Tất cả gói du lịch",
  about: "Giới thiệu",
  aboutAppTitle: "Về ứng dụng",
  aboutAppDescription:
    "Travel Explorer giúp người dùng khám phá điểm đến, lưu địa điểm yêu thích, đặt chuyến đi và nhận gợi ý du lịch AI trong một trải nghiệm di động.",
  aboutTeamTitle: "Về nhóm phát triển",
  aboutTeamDescription:
    "Chúng tôi là một nhóm sản phẩm nhỏ, tập trung làm cho việc lên kế hoạch du lịch rõ ràng, nhanh hơn và thú vị hơn bằng thiết kế chỉn chu cùng công nghệ hữu ích.",
  aboutValueAi: "Gợi ý AI",
  aboutValueExplore: "Khám phá",
  aboutValueSave: "Lưu địa điểm",
  favoritePlaces: "Địa điểm yêu thích",
  noFavorites: "Chưa có địa điểm yêu thích",
  noFavoritesMessage: "Chạm biểu tượng trái tim ở địa điểm bất kỳ để lưu tại đây.",
  search: "Tìm kiếm",
  searchPlaces: "Tìm địa điểm",
  notification: "Thông báo",
  clearAll: "Xóa tất cả",
  recent: "Gần đây",
  earlier: "Trước đó",
  archived: "Đã lưu trữ",
  aiChat: "AI Chat",
  aiTravelAssistant: "Trợ lý du lịch AI",
  aiChatSubtitle: "Hỏi lịch trình, ngân sách, hành lý và ý tưởng điểm đến.",
  askAiPlaceholder: "Hỏi AI du lịch...",
  aiQuickBeach: "Lên lịch cuối tuần biển",
  aiQuickBudget: "Gợi ý chuyến tiết kiệm",
  aiQuickPacking: "Checklist hành lý",
  aiQuickVietnam: "Lịch trình Việt Nam",
  aiThinking: "Đang nghĩ",
  cancel: "Hủy",
  viewAll: "Xem tất cả",
  bookNow: "Đặt ngay",
  bookingConfirmed: "Đặt thành công",
  bookingDetails: "Thông tin đặt chỗ",
  bookingFailed: "Không thể đặt chuyến này",
  bookings: "Đơn đặt",
  aboutDestination: "Về điểm đến",
  guests: "Số khách",
  myBookings: "Đơn đặt của tôi",
  noBookings: "Chưa có đơn đặt",
  noBookingsMessage: "Hãy đặt một điểm đến, các chuyến đã xác nhận sẽ hiện ở đây.",
  person: "Người",
  joined: "đã tham gia",
  perPerson: "Người",
  reviews: "đánh giá",
  home: "Trang chủ",
  profile: "Hồ sơ",
  editProfile: "Sửa hồ sơ",
  changeProfilePicture: "Đổi ảnh đại diện",
  rewardPoints: "Điểm thưởng",
  travelTrips: "Chuyến đi",
  bucketList: "Bucket List",
  bookmarked: "Đã lưu",
  previousTrips: "Chuyến đi trước",
  contactAndPolicy: "Liên hệ & chính sách",
  contactInfo: "Thông tin liên hệ",
  logout: "Đăng xuất",
  privacyPolicy: "Chính sách bảo mật",
  privacyPolicyText:
    "Chúng tôi chỉ thu thập thông tin cần thiết để cung cấp tài khoản, đặt chuyến, địa điểm yêu thích và trợ lý du lịch. Thông tin liên hệ được dùng cho xác thực, hỗ trợ và cập nhật chuyến đi.",
  socialNetworks: "Mạng xã hội",
  termsOfUse: "Điều khoản sử dụng",
  termsOfUseText:
    "Khi sử dụng Travel Explorer, bạn đồng ý cung cấp thông tin đặt chỗ chính xác, tuân thủ quy tắc dịch vụ và xem gợi ý AI như thông tin tham khảo du lịch.",
  verification: "Xác thực",
  version: "Phiên bản",
  done: "Xong",
  firstName: "Tên",
  lastName: "Họ",
  location: "Vị trí",
  mobileNumber: "Số điện thoại",
  otpVerification: "Xác thực OTP",
  otpDescription: "Vui lòng kiểm tra email của bạn để xem mã xác thực",
  otpCode: "Mã OTP",
  verify: "Xác thực",
  signInToBook: "Vui lòng đăng nhập để đặt điểm đến này.",
  status: "Trạng thái",
  total: "Tổng cộng",
  travelDate: "Ngày đi",
  resendCodeTo: "Gửi lại mã đến",
  theme: "Giao diện",
  lightMode: "Sáng",
  darkMode: "Tối",
  language: "Ngôn ngữ",
  english: "EN",
  vietnamese: "VI",
  noResults: "Không tìm thấy kết quả",
  noResultsMessage: "Thử từ khóa khác hoặc khám phá các địa điểm phổ biến.",
  loading: "Đang tải",
  loadDataError: "Không tải được dữ liệu ứng dụng",
  retry: "Thử lại",
};

export default vi;
